import Foundation

struct WorkBatchTaskItem: Codable, Equatable, Identifiable {
    let id: String
    var title: String
    var body: String
    var status: String
}

enum WorkBatchCockpitHost: String, Codable, Equatable {
    case claudeCode = "claude_code"
}

enum WorkBatchCockpitBindingStatus: String, Codable, Equatable {
    case launching
    case running
    case stale
    case waiting
    case done
}

struct WorkBatchCockpitBinding: Codable, Equatable, Identifiable {
    let id: String
    let batchID: String
    var batchName: String
    let projectPath: String
    let worktreeName: String
    let worktreePath: String
    let host: WorkBatchCockpitHost
    let claudeSessionID: String
    var status: WorkBatchCockpitBindingStatus
    let createdAt: Date
    var updatedAt: Date

    enum CodingKeys: String, CodingKey {
        case id
        case batchID = "batch_id"
        case batchName = "batch_name"
        case projectPath = "project_path"
        case worktreeName = "worktree_name"
        case worktreePath = "worktree_path"
        case host
        case claudeSessionID = "claude_session_id"
        case status
        case createdAt = "created_at"
        case updatedAt = "updated_at"
    }
}

struct WorkBatchCockpitBindingStore {
    private struct Envelope: Codable {
        var version: Int
        var bindings: [WorkBatchCockpitBinding]
    }

    private let fileURL: URL
    private let fileManager: FileManager

    init(
        projectPath: String,
        fileManager: FileManager = .default,
    ) {
        self.init(
            fileURL: Self.defaultFileURL(projectPath: projectPath, fileManager: fileManager),
            fileManager: fileManager,
        )
    }

    init(
        fileURL: URL,
        fileManager: FileManager = .default,
    ) {
        self.fileURL = fileURL
        self.fileManager = fileManager
    }

    static func defaultFileURL(projectPath: String, fileManager: FileManager = .default) -> URL {
        CapacitorProjectPaths.projectDataDirectory(for: projectPath, fileManager: fileManager)
            .appendingPathComponent("work-batches", isDirectory: true)
            .appendingPathComponent("cockpit-bindings.json")
    }

    func load() throws -> [WorkBatchCockpitBinding] {
        guard fileManager.fileExists(atPath: fileURL.path) else { return [] }
        let data = try Data(contentsOf: fileURL)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode(Envelope.self, from: data).bindings
    }

    func binding(batchID: String) throws -> WorkBatchCockpitBinding? {
        try load().first { $0.batchID == batchID }
    }

    func upsert(_ binding: WorkBatchCockpitBinding) throws {
        var bindings = try load()
        if let index = bindings.firstIndex(where: { $0.batchID == binding.batchID }) {
            bindings[index] = binding
        } else {
            bindings.append(binding)
        }
        try save(bindings)
    }

    func save(_ bindings: [WorkBatchCockpitBinding]) throws {
        try fileManager.createDirectory(
            at: fileURL.deletingLastPathComponent(),
            withIntermediateDirectories: true,
        )

        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        let data = try encoder.encode(Envelope(version: 1, bindings: bindings))
        try data.write(to: fileURL, options: .atomic)
    }
}

struct WorkBatchContextMirror: Equatable {
    static let relativePath = ".capacitor/work-batch-context.md"

    let batchID: String
    let batchName: String
    let projectPath: String
    let worktreePath: String
    let tasks: [WorkBatchTaskItem]
    var checkpoints: [WorkBatchCheckpointRecord] = []
    var deliveryGeneration: String?
    let updatedAt: Date

    var markdown: String {
        let updatedAtString = ISO8601DateFormatter.shared.string(from: updatedAt)
        let deliveryGenerationJSON = deliveryGeneration.map { ",\"delivery_generation\":\"\($0)\"" } ?? ""
        var lines: [String] = [
            "# Capacitor Work Batch Context",
            "",
            "Batch: \(batchName)",
            "Batch ID: \(batchID)",
            "Project: \(projectPath)",
            "Worktree: \(worktreePath)",
            "",
            "This file is generated by Capacitor. Use it as the current agent-readable view of the Work Batch while you work in this Claude Code session. Capacitor keeps canonical state outside this worktree.",
            "",
            "Keep visible terminal updates short and operator-facing, for example: \"Assessing tasks...\", \"1 task: <task name>. Starting...\", \"Done: <task name>\", or \"Needs input: <question>\". The artifact rules below are for Capacitor sync, not for narration.",
            "",
            "Before starting a queued Task, write the Task claim described below. When a Task is done, write a Done report before saying it is done. If user input is needed before continuing, ask for a checkpoint instead of guessing. If the user asks for new work in this Claude Code session, write a Task request instead of editing Capacitor state directly. If the user steers you manually in this Claude Code session, still use Task request, Task claim, Done, and Checkpoint artifacts so Capacitor can stay in sync.",
            "",
            "Task request path: \(WorkBatchTaskRequestStore.relativeDirectory)/<task-id>.json",
            "Task request JSON: {\"task_id\":\"<task-id>\",\"title\":\"short task title\",\"body\":\"what the user asked for\",\"source\":\"manual_user_instruction\",\"requested_at\":\"\(updatedAtString)\"}",
            "",
            "Task claim path: \(WorkBatchTaskClaimStore.relativeDirectory)/<task-id>.json",
            "Task claim JSON: {\"task_id\":\"<task-id>\",\"status\":\"working\",\"summary\":\"what you are doing now\",\"claimed_at\":\"\(updatedAtString)\",\"context_updated_at\":\"\(updatedAtString)\"\(deliveryGenerationJSON)}",
            "",
            "Done report path: \(WorkBatchCompletionReportStore.relativeDirectory)/<task-id>.json",
            "Done report JSON: {\"task_id\":\"<task-id>\",\"status\":\"done\",\"summary\":\"what changed\",\"evidence\":[\"specific evidence\"],\"completed_at\":\"\(updatedAtString)\"}",
            "",
            "Checkpoint request path: \(WorkBatchCheckpointRequestStore.relativeDirectory)/<checkpoint-id>.json",
            "Checkpoint request JSON: {\"checkpoint_id\":\"<checkpoint-id>\",\"task_id\":\"<task-id>\",\"question\":\"what you need from the user\",\"reason\":\"why this is needed before continuing\",\"recommended_action\":\"short suggested next action\",\"requested_at\":\"\(updatedAtString)\"}",
            "Checkpoint response path: \(WorkBatchCheckpointResponseStore.relativeDirectory)/<checkpoint-id>.json",
            "",
            "## Tasks",
            "",
        ]

        if tasks.isEmpty {
            lines.append("- No Tasks are currently queued.")
        } else {
            for task in tasks {
                lines.append("- [\(task.status)] \(task.title) (`\(task.id)`)")
                if !task.body.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                    lines.append("  \(task.body)")
                }
            }
        }

        lines.append("")
        lines.append("## Checkpoints")
        lines.append("")

        if checkpoints.isEmpty {
            lines.append("- No checkpoints are currently pending or recently answered.")
        } else {
            for checkpoint in checkpoints.sorted(by: checkpointSort) {
                lines.append("- [\(checkpoint.status.rawValue)] \(checkpoint.question) (`\(checkpoint.id)`, Task `\(checkpoint.taskID)`)")
                let reason = checkpoint.reason.trimmingCharacters(in: .whitespacesAndNewlines)
                if !reason.isEmpty {
                    lines.append("  Reason: \(reason)")
                }
                if let recommendedAction = checkpoint.recommendedAction?.trimmingCharacters(in: .whitespacesAndNewlines),
                   !recommendedAction.isEmpty
                {
                    lines.append("  Recommended action: \(recommendedAction)")
                }
                if let response = checkpoint.response?.trimmingCharacters(in: .whitespacesAndNewlines),
                   !response.isEmpty
                {
                    lines.append("  User response: \(response)")
                }
            }
        }

        lines.append("")
        lines.append("Updated: \(ISO8601DateFormatter.shared.string(from: updatedAt))")
        lines.append("")
        return lines.joined(separator: "\n")
    }

    func write(fileManager: FileManager = .default) throws -> URL {
        let url = URL(fileURLWithPath: worktreePath)
            .appendingPathComponent(Self.relativePath)
        try? WorkBatchMetadataIgnoreInstaller.install(
            in: worktreePath,
            fileManager: fileManager,
        )
        try fileManager.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true,
        )
        try markdown.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    private func checkpointSort(
        _ lhs: WorkBatchCheckpointRecord,
        _ rhs: WorkBatchCheckpointRecord,
    ) -> Bool {
        if lhs.status != rhs.status {
            return lhs.status == .pending
        }
        if lhs.updatedAt != rhs.updatedAt {
            return lhs.updatedAt > rhs.updatedAt
        }
        return lhs.id.localizedStandardCompare(rhs.id) == .orderedAscending
    }
}

struct ClaudeCodeTaskSessionLaunchRequest: Equatable {
    enum Mode: Equatable {
        case start(prompt: String)
        case resume(prompt: String?)
    }

    let worktreePath: String
    let batchName: String
    let sessionID: String
    let permissionMode: String
    let appendedSystemPrompt: String?
    let appendedSystemPromptFile: String?
    let mode: Mode

    init(
        worktreePath: String,
        batchName: String,
        sessionID: String,
        permissionMode: String = "auto",
        appendedSystemPrompt: String? = nil,
        appendedSystemPromptFile: String? = nil,
        mode: Mode,
    ) {
        self.worktreePath = worktreePath
        self.batchName = batchName
        self.sessionID = sessionID
        self.permissionMode = permissionMode
        self.appendedSystemPrompt = appendedSystemPrompt
        self.appendedSystemPromptFile = appendedSystemPromptFile
        self.mode = mode
    }

    var arguments: [String] {
        switch mode {
        case let .start(prompt):
            var values = [
                "--session-id",
                sessionID,
                "--permission-mode",
                permissionMode,
                "--name",
                batchName,
            ]
            values.append(contentsOf: appendedSystemPromptArguments)
            values.append(prompt)
            return values
        case let .resume(prompt):
            var values = [
                "--resume",
                sessionID,
                "--permission-mode",
                permissionMode,
            ]
            values.append(contentsOf: appendedSystemPromptArguments)
            if let prompt {
                values.append(prompt)
            }
            return values
        }
    }

    private var appendedSystemPromptArguments: [String] {
        if let file = appendedSystemPromptFile?.trimmingCharacters(in: .whitespacesAndNewlines),
           !file.isEmpty
        {
            return ["--append-system-prompt-file", file]
        }
        guard let prompt = appendedSystemPrompt?.trimmingCharacters(in: .whitespacesAndNewlines),
              !prompt.isEmpty
        else {
            return []
        }
        return ["--append-system-prompt", prompt]
    }

    func command(claudePath: String) -> String {
        ([claudePath] + arguments)
            .map(shellEscape)
            .joined(separator: " ")
    }
}

struct WorkBatchTaskSessionStartRequest: Equatable {
    let projectPath: String
    let batchID: String
    let batchName: String
    let tasks: [WorkBatchTaskItem]
    let deliveryGeneration: String?
    let assignedSessionID: String?
    let now: Date

    init(
        projectPath: String,
        batchID: String,
        batchName: String,
        tasks: [WorkBatchTaskItem],
        deliveryGeneration: String? = nil,
        assignedSessionID: String? = nil,
        now: Date = Date(),
    ) {
        self.projectPath = projectPath
        self.batchID = batchID
        self.batchName = batchName
        self.tasks = tasks
        self.deliveryGeneration = deliveryGeneration
        self.assignedSessionID = assignedSessionID
        self.now = now
    }
}

struct WorkBatchTaskSessionStartResult: Equatable {
    let binding: WorkBatchCockpitBinding
    let contextMirrorURL: URL
    let actionableContextDigest: String?
    let launchRequest: ClaudeCodeTaskSessionLaunchRequest
}

enum WorkBatchTaskSessionError: Error, Equatable, LocalizedError {
    case claudeNotFound
    case existingSessionFocusFailed
    case existingSessionWakeFailed
    case terminalLaunchFailed(exitCode: Int32, output: String?)

    var errorDescription: String? {
        switch self {
        case .claudeNotFound:
            return "Claude CLI not found"
        case .existingSessionFocusFailed:
            return "Could not focus the existing Claude Code session"
        case .existingSessionWakeFailed:
            return "Could not wake the existing Claude Code session"
        case let .terminalLaunchFailed(exitCode, output):
            let detail = output?.trimmingCharacters(in: .whitespacesAndNewlines)
            if let detail, !detail.isEmpty {
                return "Claude Code launch failed with exit code \(exitCode): \(detail)"
            }
            return "Claude Code launch failed with exit code \(exitCode)"
        }
    }
}

@MainActor
final class WorkBatchTaskSessionCoordinator {
    static let agentInstructionsRelativePath = ".capacitor/work-batch-agent-instructions.md"

    typealias ClaudePathResolver = @Sendable () async -> String?
    typealias SessionIDGenerator = @Sendable () -> String
    typealias TerminalScriptRunner = @Sendable (String) async throws -> Void
    typealias ExistingTerminalFocuser = @Sendable (String, String?) async -> Bool
    typealias ExistingTerminalWaker = @Sendable (String, String?, String) async -> Bool
    typealias BindingStoreFactory = (String) -> WorkBatchCockpitBindingStore

    private let worktreeService: WorktreeService
    private let fileManager: FileManager
    private let claudePathResolver: ClaudePathResolver
    private let sessionIDGenerator: SessionIDGenerator
    private let runTerminalScript: TerminalScriptRunner
    private let focusExistingTerminal: ExistingTerminalFocuser
    private let wakeExistingTerminal: ExistingTerminalWaker
    private let bindingStoreFactory: BindingStoreFactory

    init(
        worktreeService: WorktreeService = WorktreeService(),
        fileManager: FileManager = .default,
        claudePathResolver: @escaping ClaudePathResolver = {
            await ClaudeCliResolver.shared.resolveClaudePath()
        },
        sessionIDGenerator: @escaping SessionIDGenerator = {
            UUID().uuidString.lowercased()
        },
        runTerminalScript: @escaping TerminalScriptRunner = { script in
            let result = await TerminalLauncher.runBashScriptWithResult(script)
            guard result.exitCode == 0 else {
                throw WorkBatchTaskSessionError.terminalLaunchFailed(
                    exitCode: result.exitCode,
                    output: result.output,
                )
            }
        },
        focusExistingTerminal: @escaping ExistingTerminalFocuser = { projectPath, sessionName in
            await TerminalLauncher().focusExistingTerminal(
                projectPath: projectPath,
                sessionName: sessionName,
            )
        },
        wakeExistingTerminal: ExistingTerminalWaker? = nil,
        bindingStoreFactory: BindingStoreFactory? = nil,
    ) {
        self.worktreeService = worktreeService
        self.fileManager = fileManager
        self.claudePathResolver = claudePathResolver
        self.sessionIDGenerator = sessionIDGenerator
        self.runTerminalScript = runTerminalScript
        self.focusExistingTerminal = focusExistingTerminal
        let defaultWaker = WorkBatchGhosttySessionWaker()
        self.wakeExistingTerminal = wakeExistingTerminal ?? { projectPath, sessionName, prompt in
            defaultWaker.wake(
                worktreePath: projectPath,
                batchName: sessionName,
                prompt: prompt,
            )
        }
        self.bindingStoreFactory = bindingStoreFactory ?? { projectPath in
            WorkBatchCockpitBindingStore(projectPath: projectPath)
        }
    }

    func startNewSession(_ request: WorkBatchTaskSessionStartRequest) async throws -> WorkBatchTaskSessionStartResult {
        guard let claudePath = await claudePathResolver() else {
            throw WorkBatchTaskSessionError.claudeNotFound
        }

        let worktreeName = Self.worktreeName(batchID: request.batchID)
        let branchName = "pkp/\(worktreeName)"
        let sessionID = request.assignedSessionID ?? sessionIDGenerator()

        let worktree = try worktreeService.createManagedWorktree(
            in: request.projectPath,
            name: worktreeName,
            branchName: branchName,
        )

        let mirror = WorkBatchContextMirror(
            batchID: request.batchID,
            batchName: request.batchName,
            projectPath: request.projectPath,
            worktreePath: worktree.path,
            tasks: request.tasks,
            deliveryGeneration: request.deliveryGeneration,
            updatedAt: request.now,
        )
        let actionableContextDigest = WorkBatchActionableContext.digest(
            batchID: request.batchID,
            tasks: request.tasks,
            checkpoints: [],
        )
        let mirrorURL = try mirror.write(fileManager: fileManager)
        _ = try writeAgentInstructions(worktreePath: worktree.path)

        // New Work Batch path: Capacitor owns the Claude session id before launch.
        // Legacy delegation/project-creation paths still discover session ids after launch.
        let binding = WorkBatchCockpitBinding(
            id: request.batchID,
            batchID: request.batchID,
            batchName: request.batchName,
            projectPath: request.projectPath,
            worktreeName: worktreeName,
            worktreePath: worktree.path,
            host: .claudeCode,
            claudeSessionID: sessionID,
            status: .launching,
            createdAt: request.now,
            updatedAt: request.now,
        )

        let launchRequest = ClaudeCodeTaskSessionLaunchRequest(
            worktreePath: worktree.path,
            batchName: request.batchName,
            sessionID: sessionID,
            appendedSystemPromptFile: Self.agentInstructionsRelativePath,
            mode: .start(prompt: Self.initialPrompt(contextMirrorRelativePath: WorkBatchContextMirror.relativePath)),
        )
        let script = TerminalScripts.launchWithCommand(
            projectPath: worktree.path,
            command: launchRequest.command(claudePath: claudePath),
        )
        try await runTerminalScript(script)
        try bindingStoreFactory(request.projectPath).upsert(binding)

        return WorkBatchTaskSessionStartResult(
            binding: binding,
            contextMirrorURL: mirrorURL,
            actionableContextDigest: actionableContextDigest,
            launchRequest: launchRequest,
        )
    }

    func resumeRequest(
        for binding: WorkBatchCockpitBinding,
        prompt: String? = nil,
    ) -> ClaudeCodeTaskSessionLaunchRequest {
        ClaudeCodeTaskSessionLaunchRequest(
            worktreePath: binding.worktreePath,
            batchName: binding.batchName,
            sessionID: binding.claudeSessionID,
            appendedSystemPromptFile: Self.agentInstructionsRelativePath,
            mode: .resume(prompt: prompt),
        )
    }

    func openExistingSession(
        _ binding: WorkBatchCockpitBinding,
        allowResumeWhenFocusFails: Bool = false,
        preferFocusBeforeResume: Bool = false,
        prompt: String? = nil,
    ) async throws -> ClaudeCodeTaskSessionLaunchRequest? {
        if preferFocusBeforeResume || shouldFocusBeforeResume(binding.status) {
            if await focusExistingTerminal(binding.worktreePath, binding.batchName) {
                TerminalActivationTrace.log(
                    surface: .workBatchSession,
                    route: "work_batch_cockpit",
                    projectPath: binding.worktreePath,
                    batchID: binding.batchID,
                    batchName: binding.batchName,
                    sessionName: binding.claudeSessionID,
                    evidence: ["batch_binding", "visible_terminal"],
                    action: "focus_existing",
                    outcome: "focused",
                )
                return nil
            }
            guard allowResumeWhenFocusFails else {
                TerminalActivationTrace.log(
                    surface: .workBatchSession,
                    route: "work_batch_cockpit",
                    projectPath: binding.worktreePath,
                    batchID: binding.batchID,
                    batchName: binding.batchName,
                    sessionName: binding.claudeSessionID,
                    evidence: ["batch_binding", "focus_failed", "resume_not_allowed"],
                    action: "bail",
                    outcome: "focus_failed",
                )
                throw WorkBatchTaskSessionError.existingSessionFocusFailed
            }
        }

        guard let claudePath = await claudePathResolver() else {
            TerminalActivationTrace.log(
                surface: .workBatchSession,
                route: "claude_resume",
                projectPath: binding.worktreePath,
                batchID: binding.batchID,
                batchName: binding.batchName,
                sessionName: binding.claudeSessionID,
                evidence: ["batch_binding"],
                action: "resolve_claude",
                outcome: "failed",
                reason: "claude_not_found",
            )
            throw WorkBatchTaskSessionError.claudeNotFound
        }

        _ = try writeAgentInstructions(worktreePath: binding.worktreePath)
        let request = resumeRequest(
            for: binding,
            prompt: prompt,
        )
        let script = TerminalScripts.launchWithCommand(
            projectPath: binding.worktreePath,
            command: request.command(claudePath: claudePath),
        )
        try await runTerminalScript(script)
        TerminalActivationTrace.log(
            surface: .workBatchSession,
            route: "claude_resume",
            projectPath: binding.worktreePath,
            batchID: binding.batchID,
            batchName: binding.batchName,
            sessionName: binding.claudeSessionID,
            evidence: ["batch_binding", "context_mirror"],
            action: "resume_claude",
            outcome: "launched",
        )
        return request
    }

    func wakeExistingSession(_ binding: WorkBatchCockpitBinding, prompt: String) async throws {
        guard await wakeExistingTerminal(binding.worktreePath, binding.batchName, prompt) else {
            TerminalActivationTrace.log(
                surface: .workBatchSession,
                route: "claude_wake",
                projectPath: binding.worktreePath,
                batchID: binding.batchID,
                batchName: binding.batchName,
                sessionName: binding.claudeSessionID,
                evidence: ["batch_binding", "terminal_input"],
                action: "wake_existing",
                outcome: "failed",
            )
            throw WorkBatchTaskSessionError.existingSessionWakeFailed
        }
        TerminalActivationTrace.log(
            surface: .workBatchSession,
            route: "claude_wake",
            projectPath: binding.worktreePath,
            batchID: binding.batchID,
            batchName: binding.batchName,
            sessionName: binding.claudeSessionID,
            evidence: ["batch_binding", "terminal_input"],
            action: "wake_existing",
            outcome: "delivered",
        )
    }

    private func shouldFocusBeforeResume(_ status: WorkBatchCockpitBindingStatus) -> Bool {
        switch status {
        case .launching, .running:
            // New Work Batch behavior: visible Claude Code cockpits should be
            // re-entered in place. Legacy delegation paths still reconnect by
            // launching/resuming through their own coordinator.
            true
        case .stale, .waiting, .done:
            false
        }
    }

    nonisolated static func worktreeName(batchID: String) -> String {
        let sanitized = batchID.lowercased().map { character -> Character in
            if character.isLetter || character.isNumber || character == "-" || character == "_" {
                return character
            }
            return "-"
        }
        let collapsed = String(sanitized)
            .split(separator: "-", omittingEmptySubsequences: true)
            .joined(separator: "-")
        let suffix = collapsed.isEmpty ? UUID().uuidString.lowercased() : collapsed
        let prefixed = suffix.hasPrefix("batch-") ? suffix : "batch-\(suffix)"
        return String(prefixed.prefix(38))
    }

    nonisolated static func initialPrompt(contextMirrorRelativePath _: String) -> String {
        "Assessing tasks..."
    }

    nonisolated static func agentInstructionsPrompt(contextMirrorRelativePath: String) -> String {
        [
            "Capacitor is managing this Work Batch.",
            "Read \(contextMirrorRelativePath) before acting and treat it as the current agent-readable view.",
            "Start queued Tasks without asking for more detail when the path is reasonably clear.",
            "Before starting a queued Task, write the Task claim described in the context mirror.",
            "When a Task is done, write the Done report before saying it is done.",
            "If user input is needed before continuing, write a Checkpoint request instead of guessing.",
            "If the user asks for new work in this Claude Code session, write a Task request instead of editing Capacitor state directly.",
            "If the user steers you manually in this Claude Code session, keep Task request, claim, Done, and Checkpoint artifacts in sync so Capacitor can stay honest.",
            "Keep visible terminal updates short and operator-facing, such as \"1 task: <task name>. Starting...\", \"Done: <task name>\", or \"Needs input: <question>\".",
            "Do not narrate Capacitor artifact mechanics unless the user asks.",
        ].joined(separator: " ")
    }

    private func writeAgentInstructions(worktreePath: String) throws -> URL {
        let url = URL(fileURLWithPath: worktreePath)
            .appendingPathComponent(Self.agentInstructionsRelativePath)
        try? WorkBatchMetadataIgnoreInstaller.install(
            in: worktreePath,
            fileManager: fileManager,
        )
        try fileManager.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true,
        )
        try Self.agentInstructionsPrompt(contextMirrorRelativePath: WorkBatchContextMirror.relativePath)
            .write(to: url, atomically: true, encoding: .utf8)
        return url
    }
}
