from __future__ import annotations

import importlib.util
import pathlib
import sys
import tempfile
import textwrap
import unittest


ROOT = pathlib.Path(__file__).resolve().parents[3]
SCRIPTS_DIR = ROOT / "scripts/verify"
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))
for site_packages in sorted((ROOT / ".verifier/.venv/lib").glob("python*/site-packages")):
    if str(site_packages) not in sys.path:
        sys.path.insert(0, str(site_packages))


def load_module(name: str, relative_path: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / relative_path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Unable to load module {relative_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


class ExtractorTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.extractor = load_module("extract_facts", "scripts/verify/extract-facts.py")

    def test_extract_module_marks_generated_bridge_surface(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = pathlib.Path(temp_dir)
            path = repo_root / "apps/swift/Sources/Capacitor/Bridge/capacitor_core.swift"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                textwrap.dedent(
                    """\
                    // This file was autogenerated by some hot garbage in the `uniffi` crate.
                    // swiftlint:disable all
                    import Foundation
                    """
                )
            )

            module = self.extractor.extract_module(path, repo_root)

            self.assertTrue(module["generated"])

    def test_ast_references_ignore_strings_and_comments_but_keep_provenance(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = pathlib.Path(temp_dir)
            path = repo_root / "apps/swift/Sources/Capacitor/Models/Foo.swift"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                textwrap.dedent(
                    """\
                    import Foundation

                    // detectAvailable should not count from comments
                    struct Foo {
                        func run() {
                            let detectAvailable = "preferredTmuxPaneFromShellState"
                            helper(detectAvailable)
                        }
                    }
                    """
                )
            )

            module = self.extractor.extract_module(path, repo_root)
            reference_values = {entry["value"] for entry in module["references"]}
            call_values = {entry["value"] for entry in module["calls"]}

            self.assertIn("detectAvailable", reference_values)
            self.assertIn("helper", call_values)
            self.assertNotIn("preferredTmuxPaneFromShellState", reference_values)

            detect_available_entries = [entry for entry in module["references"] if entry["value"] == "detectAvailable"]
            self.assertTrue(detect_available_entries)
            for entry in detect_available_entries:
                self.assertEqual("reference", entry["kind"])
                self.assertEqual("swift", entry["language"])
                self.assertEqual("medium", entry["confidence"])
                self.assertIn("source_span", entry)

    def test_ast_call_and_import_entries_carry_fact_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = pathlib.Path(temp_dir)
            path = repo_root / "core/example/src/lib.rs"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                textwrap.dedent(
                    """\
                    use crate::foo::Bar;

                    pub fn run() {
                        foo::bar();
                    }
                    """
                )
            )

            module = self.extractor.extract_module(path, repo_root)

            self.assertEqual("import", module["imports"][0]["kind"])
            self.assertEqual("call", module["calls"][0]["kind"])
            self.assertEqual("rust", module["calls"][0]["language"])
            self.assertIn("source_span", module["calls"][0])

    def test_runtime_artifact_paths_do_not_count_as_http_routes(self) -> None:
        with tempfile.TemporaryDirectory() as temp_dir:
            repo_root = pathlib.Path(temp_dir)
            path = repo_root / "apps/swift/Sources/Capacitor/Utilities/DebugLog.swift"
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(
                textwrap.dedent(
                    """\
                    import Foundation

                    let path = ".capacitor/runtime/app-debug.log"
                    """
                )
            )

            module = self.extractor.extract_module(path, repo_root)

            self.assertEqual([], module["http_routes"])


if __name__ == "__main__":
    unittest.main()
